/* Optional real-browser test. Requires Playwright only for QA, not for the app.
   npm install --no-save playwright && npx playwright install chromium
   node tests/browser_e2e.cjs
   SANA_PYTHON, SANA_PLAYWRIGHT_MODULE, SANA_CHROMIUM_PATH are optional overrides. */
const {spawn}=require('node:child_process');
const fs=require('node:fs');
const path=require('node:path');
const os=require('node:os');
const assert=require('node:assert/strict');
const {chromium}=require(process.env.SANA_PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..');
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'sana-e2e-'));
const shots=process.env.SANA_SCREENSHOTS||path.join(temp,'screenshots');
fs.mkdirSync(shots,{recursive:true});
const python=process.env.SANA_PYTHON||(process.platform==='win32'?'python':'python3');
const server=spawn(python,[path.join(root,'server.py'),'--port','0','--db',path.join(temp,'qa.sqlite3')],{env:{...process.env,SANA_QUIET:'1'}});
let browser;
const waitForServer=new Promise((resolve,reject)=>{
 let output='';server.stdout.on('data',chunk=>{output+=chunk.toString();const found=output.match(/http:\/\/127\.0\.0\.1:(\d+)/);if(found)resolve(found[0]);});
 server.on('error',reject);server.on('exit',code=>{if(code)reject(new Error('Server stopped: '+code));});
 server.stderr.on('data',data=>process.stderr.write(data));
});
(async()=>{
 const base=await waitForServer;
 browser=await chromium.launch({headless:true,...(process.env.SANA_CHROMIUM_PATH?{executablePath:process.env.SANA_CHROMIUM_PATH}:{}),args:['--no-sandbox','--disable-dev-shm-usage','--no-zygote']});
 const page=await browser.newPage({viewport:{width:1440,height:1050}});
 page.setDefaultTimeout(12000);
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base);
 await page.getByRole('heading',{name:'Идеялар іске айналады.'}).waitFor();
 assert.equal(await page.locator('.task-card').count(),5);
 await page.screenshot({path:path.join(shots,'01-catalog.png'),fullPage:true});
 await page.locator('#level-filter').selectOption('draft');assert.equal(await page.locator('.task-card').count(),1);
 await page.locator('#level-filter').selectOption('');
 await page.getByRole('button',{name:'Демонстрация',exact:true}).click();
 await page.getByRole('button',{name:'Демоны бастау',exact:true}).click();
 await page.getByRole('button',{name:'Талдау және нақтылау',exact:true}).click();
 await page.locator('#questions-form').waitFor();
 assert.ok(await page.locator('#questions-form textarea').count()>=3);
 await page.getByRole('button',{name:'Демо жауаптарды қою',exact:true}).click();
 await page.getByRole('button',{name:'Карточканы қалыптастыру',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('.score-number')?.textContent.includes('0 / 100'));
 await page.locator('[data-confirm="data"]').check();
 await page.waitForFunction(()=>document.querySelector('.score-number')?.textContent.includes('20 / 100'));
 await page.locator('[data-confirm="context"]').check();
 await page.locator('[data-confirm="need"]').check();
 await page.waitForFunction(()=>document.querySelector('.score-number')?.textContent.includes('40 / 100'));
 await page.getByRole('button',{name:'Барлығын оқыдым, растаймын',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('.score-number')?.textContent.includes('100 / 100'));
 const original=await page.locator('#card-data').inputValue();
 await page.locator('#card-data').fill('');
 await page.waitForFunction(()=>document.querySelector('.score-number')?.textContent.includes('80 / 100'));
 assert.equal(await page.locator('[data-confirm="data"]').isChecked(),false);
 await page.locator('#card-data').fill(original);
 await page.locator('[data-confirm="data"]').check();
 await page.waitForFunction(()=>document.querySelector('.score-number')?.textContent.includes('100 / 100'));
 await page.evaluate(()=>{window.scrollTo(0,0);document.querySelector('#toast').classList.remove('show');});
 await page.screenshot({path:path.join(shots,'02-rating-editor.png'),fullPage:true});
 await page.getByRole('button',{name:'Растап, жариялау',exact:true}).click();
 const title='Күнделікті қорды автоматты бақылау';
 await page.getByRole('heading',{name:title,exact:true}).waitFor();
 await page.getByRole('button',{name:'Студент',exact:true}).click();
 await page.getByRole('button',{name:'Ұсыныс беру',exact:true}).first().click();
 await page.getByRole('button',{name:'Демо мысалды қою',exact:true}).click();
 await page.getByRole('button',{name:'Ұсынысты жіберу',exact:true}).click();
 let proposal=page.locator('.proposal').filter({hasText:title});
 await proposal.getByText('Қаралуда',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Бизнес',exact:true}).click();
 await proposal.getByRole('button',{name:'Команданы таңдау',exact:true}).click();
 await page.getByRole('button',{name:'Шешімді растау',exact:true}).click();
 await proposal.getByText('Таңдалды',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Студент',exact:true}).click();
 await proposal.getByRole('button',{name:'Кезең нәтижесін жіберу',exact:true}).click();
 await page.getByRole('button',{name:'Демо мысалды қою',exact:true}).click();
 await page.getByRole('button',{name:'Бизнеске жіберу',exact:true}).click();
 await proposal.getByText('Растау күтілуде',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Бизнес',exact:true}).click();
 await proposal.getByRole('button',{name:'Нәтижені растау',exact:true}).click();
 await page.getByRole('button',{name:'Растау және ұпай беру',exact:true}).click();
 await proposal.getByText('Расталды',{exact:true}).waitFor();
 await page.evaluate(()=>{window.scrollTo(0,0);document.querySelector('#toast').classList.remove('show');});
 await page.screenshot({path:path.join(shots,'03-confirmed-result.png'),fullPage:true});
 await page.getByRole('button',{name:'Командалар',exact:true}).click();
 await page.locator('.team-card').filter({hasText:'Qadam Lab'}).getByText('30 ұпай',{exact:true}).waitFor();
 await page.screenshot({path:path.join(shots,'04-team-points.png'),fullPage:true});
 await page.reload();
 await page.getByRole('heading',{name:'Идеялар іске айналады.'}).waitFor();
 assert.equal(await page.locator('.task-card').count(),6);
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:path.join(shots,'05-mobile.png'),fullPage:true});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'no horizontal page overflow');
 assert.deepEqual(errors,[],'no browser JavaScript errors');
 console.log('PASS: browser E2E — clarification, rating 0→20→40→100, edit→80→100, publish, offer, manual selection, stage approval, +30, reload, mobile overflow.');
 console.log('Screenshots: '+shots);
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();server.kill();});
